name: cypress nopCommerce test
on: [push]
jobs:
  sypress-run:
      runs-on: macos-latest

      steps:
      - name: Checkout
       uses: actions/checkout@v3.5.2

      - name: Install dependencies
        run: npm ci 

      - name: Run Cypress tests
        run: npm run test:cypress


